name: Deploy playoddeve

on:
  push:
    branches:
      - main

jobs:
  productionDeployment:
    name: production deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - run: npm ci
    - name: Install Plugin and Deploy
      uses: serverless/github-action@v2
      with:
        args: -c "serverless plugin install --name serverless-go-plugin && npm run deploy:prod"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}