name: Deploy playoddeve

on:
  push:
    branches:
      - master

jobs:
  productionDeployment:
    name: production deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - run: npm ci
    - run: npm i -D serverless-go-plugin && npm run deploy:prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}