name: Deploy Code

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Serverless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install dependencies
        run: npm ci

      - run: go version
      - run: npm i -g serverless

      - name: Create profile for user
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: staging
          region: us-west-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: serverless deploy --aws-profile prod
