name: Deploy playoddeve

on:
  push:
    branches:
      - master

jobs:
  productionDeployment:
    name: production deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17 
      id: go
    - run: npm ci
    - name: Install Plugin and Deploy
      uses: serverless/github-action@v3
      with:
        args: -c "npm i && npm run deploy:prod"
        entrypoint: /home/runner/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}