name: Deploy golang code using serverless

on:
  pull_request:
    branches: 
      - master

env:
  TABLE_GAME: playoddeve-Game-prod
  AWS_REGION: ap-south-1

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs:
      build-and-verify: ${{ steps.set-output-defaults.outputs.build-and-verify }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "::set-output name=build-and-verify::${{ github.event.inputs.build-and-verify || true }}"
  
  deploy:
    needs: [EnvSetup]
    uses: yash-dxt/reusable-workflow/.github/workflows/staging-checks.yml@main
    secrets: inherit
    with:
      build-and-verify: ${{needs.EnvSetup.outputs.build-and-verify}}

      # - name: Install dependencies
      #   run: npm ci

      # - name: Configure AWS Credentials
      #   run: serverless config credentials 
      #     --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
      #     --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      #     --profile prod

      # - name: Deploy serverless
      #   run: serverless deploy --aws-profile prod
