name: Deploy golang code using serverless

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Install deps & then deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install serverless
        run: npm i -g serverless

      - name: Configure AWS Credentials
        run: serverless config credentials 
          --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          --profile default

      - run: export TABLE_GAME=playoddeve-Game-prod AWS_REGION=ap-south-1
      - run: echo $TABLE_GAME
      - run: echo $AWS_REGION


      - name: run go test case
        run: go test ./...

      - name: Install dependencies
        run: npm ci


      - name: Configure AWS Credentials
        run: serverless config credentials 
          --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          --profile prod

      - name: Deploy serverless
        run: serverless deploy --aws-profile prod
