name: Deploy golang code using serverless

on:
  pull_request:
    branches: 
      - master


env:
  TABLE_GAME: playoddeve-Game-prod
  AWS_REGION: ap-south-1

jobs:
  deploy:
    uses: yash-dxt/reusable-workflow/.github/workflows/staging-checks.yml@main
    secrets: inherit

      # - name: Install dependencies
      #   run: npm ci

      # - name: Configure AWS Credentials
      #   run: serverless config credentials 
      #     --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
      #     --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      #     --profile prod

      # - name: Deploy serverless
      #   run: serverless deploy --aws-profile prod
