name: Deploy 'em all 

on:
  push:
    branches: 
      - master
    # types: [opened, closed]

jobs:
  staging-checks:
    # if: github.event.action == 'opened' || github.event.action== 'push'
    uses: yash-dxt/reusable-workflow/.github/workflows/deploy-staging.yml@main
    secrets: inherit
  # deploy-prod:
  #   # if: github.event.action == 'closed' && github.event.pull_request.merged == true
  #   uses: yash-dxt/reusable-workflow/.github/workflows/deploy-prod.yml@main
  #   secrets: inherit