name: Deploy 'em all 

on:
  pull_request:
    branches: 
      - master
    types: [opened, closed]

jobs:
  staging-checks:
    if: github.event.action == 'open' 
    uses: yash-dxt/reusable-workflow/.github/workflows/deploy-staging.yml@main
    secrets: inherit
  deploy-prod:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: yash-dxt/reusable-workflow/.github/workflows/deploy-prod.yml@main
    secrets: inherit