name: Deploy Code

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Serverless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install dependencies
        run: npm ci

      - name: Install Go plugin
        run: npm install --save-dev serverless-go-plugin

      - name: Deploy with Serverless
        uses: serverless/github-action@v3
        with:
          args: deploy --aws-profile prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}