name: Deploy golang code using serverless

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Install deps & then deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install dependencies
        run: npm ci

      - name: Create profile for user (currently - prod)
        run: aws configure --profile prod set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} &&
            aws set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: serverless deploy --aws-profile prod
